---
driver:
  name: vagrant
  provider: libvirt

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[dmlb2000_pipeline::default]
    attributes:
