---
driver:
  name: vagrant
  provider: libvirt
  vagrantfiles:
   - Vagrantfile.storage

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1

suites:
  - name: database
    run_list:
      - recipe[dmlb2000_pipeline::database]
  - name: gerrit
    run_list:
      - recipe[dmlb2000_pipeline::gerrit]
  - name: jenkins
    run_list:
      - recipe[dmlb2000_pipeline::jenkins]
  - name: default
    run_list:
      - recipe[dmlb2000_pipeline::default]
