---
driver:
  name: vagrant
  provider: libvirt
  customize:
    volume_cache: "\'writeback\'"

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[dmlb2000_buildbot::default]
    attributes:
  - name: aio
    run_list:
      - recipe[dmlb2000_buildbot::master]
      - recipe[dmlb2000_buildbot::slave]
    attributes:
