name 'dmlb2000_pipeline'
maintainer 'David Brown'
maintainer_email 'dmlb2000@gmail.com'
license 'all_rights'
description 'Installs/Configures dmlb2000_pipeline'
long_description 'Installs/Configures dmlb2000_pipeline'
version '0.1.21'

depends 'yum-centos'
depends 'yum-epel'
depends 'python'
depends 'git'
depends 'dmlb2000_chef'
depends 'systemd'
